[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "membership_dashboard"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.9"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/membership_dashboard" }
dependencies = [
    "dash==2.15.0",
    "dash-bootstrap-components==1.5.0",
    "dash-bootstrap-templates==1.1.2",
    "mapbox==0.18.1",
    "pandas==2.2.0",
    "pandera==0.18.0",
    "plotly==5.18.0",
    "python-dotenv==1.0.1",
    "ratelimit==2.2.1",
    "tqdm==4.66.2"
]

[project.optional-dependencies]
dev = [
    "pre-commit==3.6.1",
    "pytest==8.0.0",
    "ruff==0.2.1"
]
github-actions = [
    "pytest==8.0.0",
    "pytest-emoji==0.2.0",
    "pytest-md==0.2.0",
    "ruff==0.2.1",
    "ydiff==1.2"
]
