[tool.ruff]
line-length = 160

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F"]
extend-select = ["B", "W", "C"]
ignore = ["C400", "C401"]

[project]
name = "membership_dashboard"
version = "1.0.0"
readme = "README.md"
requires-python = ">=3.10"
license = { "file" = "LICENSE" }
authors = [{ "name" = "bmos", "email" = "wil.t.dsa@pm.me" }]
urls = { "GitHub" = "https://github.com/MaineDSA/membership_dashboard" }
dependencies = [
    "dash==2.18.2",
    "dash-bootstrap-components==1.6.0",
    "dash-bootstrap-templates==1.3.0",
    "mapbox==0.18.1",
    "numpy>=1.26.4,<3",
    "pandas==2.2.3",
    "pandera==0.20.4",
    "plotly==5.24.1",
    "python-dotenv==1.0.1",
    "ratelimit==2.2.1",
    "tqdm==4.67.0"
]

[project.optional-dependencies]
dev = [
    "pre-commit==4.0.1",
    "pytest==8.3.3",
    "ruff==0.7.3"
]
github-actions = [
    "pytest-cov==6.0.0",
]
