name: Ruff

on:
  push:
    paths:
      - "**.py"
      - .github/workflows/lint-python.yml
      - pyproject.toml
  pull_request:
    paths:
      - "**.py"
      - pyproject.toml
  workflow_dispatch:

jobs:
  ruff:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        python-version:
          # - "3.12"
          # - "3.11"
          - "3.10"
          - "3.9"

    runs-on: ${{ matrix.os }}

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install uv
        run: |
          pip install -U uv

      - name: Install dependencies
        run: |
          uv pip install --system -U pip
          uv pip install --system -e .[dev]
          uv pip install --system -e .[github-actions]
          
      - name: Lint the code with ruff
        run: |
          ruff check $(git ls-files '*.py') --output-format sarif -o results.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
          category: ruff